#!/bin/bash

# Anik Dutta

# MSMC-IM (Isolation-Migration). Use the *_combined.txt file generated by combineCrossCoal.py in the 17.2.MSMC2_crosscoal.sh. I am not sure about this analysis and did not finish it. 

# Source: https://github.com/wangke16/MSMC-IM

python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta 1e-8,1e-2 -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/1963_2931.haps --printfittingdetails --plotfittingdetails --xlog 1963_2931_combined.txt 

for a in 1e-9 1e-8 1e-7; do for b in 1e-2 1e-3 1e-4 1e-5 1e-6; do python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta ${a},${b} -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/MSMC_IM/1963_2747.haps --printfittingdetails --plotfittingdetails --xlog 1963_2747_combined.txt; done; done

for a in 1e-9 1e-8 1e-7; do for b in 1e-2 1e-3 1e-4 1e-5 1e-6; do python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta ${a},${b} -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/MSMC_IM/1963_3111.haps --printfittingdetails --plotfittingdetails --xlog 1963_3111_combined.txt; done; done

for a in 1e-9 1e-8 1e-7; do for b in 1e-2 1e-3 1e-4 1e-5 1e-6; do python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta ${a},${b} -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/MSMC_IM/1963_2747.haps --printfittingdetails --plotfittingdetails --xlog 1963_4330_combined.txt; done; done

for a in 1e-9 1e-8 1e-7; do for b in 1e-2 1e-3 1e-4 1e-5 1e-6; do python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta ${a},${b} -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/MSMC_IM/1963_2932.haps --printfittingdetails --plotfittingdetails --xlog 1963_2932_combined.txt; done; done

for a in 1e-9 1e-8 1e-7; do for b in 1e-2 1e-3 1e-4 1e-5 1e-6; do python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta ${a},${b} -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/MSMC_IM/1958_3111.haps --printfittingdetails --plotfittingdetails --xlog 1958_3111_combined.txt; done; done

for a in 1e-9 1e-8 1e-7; do for b in 1e-2 1e-3 1e-4 1e-5 1e-6; do python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta ${a},${b} -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/MSMC_IM/1958_2931.haps --printfittingdetails --plotfittingdetails --xlog 1958_2931_combined.txt; done; done

for a in 1e-9 1e-8 1e-7; do for b in 1e-2 1e-3 1e-4 1e-5 1e-6; do python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta ${a},${b} -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/MSMC_IM/1958_2932.haps --printfittingdetails --plotfittingdetails --xlog 1958_2932_combined.txt; done; done

for a in 1e-9 1e-8 1e-7; do for b in 1e-2 1e-3 1e-4 1e-5 1e-6; do python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta ${a},${b} -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/MSMC_IM/1958_4117.haps --printfittingdetails --plotfittingdetails --xlog 1958_4117_combined.txt; done; done

for a in 1e-9 1e-8 1e-7; do for b in 1e-2 1e-3 1e-4 1e-5 1e-6; do python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta ${a},${b} -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/MSMC_IM/2747_3111.haps --printfittingdetails --plotfittingdetails --xlog 2747_3111_combined.txt; done; done

for a in 1e-9 1e-8 1e-7; do for b in 1e-2 1e-3 1e-4 1e-5 1e-6; do python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta ${a},${b} -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/MSMC_IM/2747_1958.haps --printfittingdetails --plotfittingdetails --xlog 2747_1958_combined.txt; done; done

for a in 1e-9 1e-8 1e-7; do for b in 1e-2 1e-3 1e-4 1e-5 1e-6; do python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta ${a},${b} -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/MSMC_IM/2747_2931.haps --printfittingdetails --plotfittingdetails --xlog 2747_2931_combined.txt; done; done

for a in 1e-9 1e-8 1e-7; do for b in 1e-2 1e-3 1e-4 1e-5 1e-6; do python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta ${a},${b} -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/MSMC_IM/2747_2932.haps --printfittingdetails --plotfittingdetails --xlog 2747_2932_combined.txt; done; done

for a in 1e-9 1e-8 1e-7; do for b in 1e-2 1e-3 1e-4 1e-5 1e-6; do python /gxfs_home/cau/suaph275/MSMC-IM/MSMC_IM.py -beta ${a},${b} -mu 1e-8 -o /gxfs_work1/cau/suaph275/MSMC_analysis/Combined_input/MSMC_IM/2747_4330.haps --printfittingdetails --plotfittingdetails --xlog 2747_4330_combined.txt; done; done

## deleting the  c='orange', in the 96th line of plot_utils.py removes the error and u can plot M(t).