# Anik Dutta
# Script to plot demographic patterns using the outputs from MSMC2

# probable mutation rate
mu <- 1e-8 
# probable generation time 
gen <- 5 

# Read the result file of each population from MSMC2 (code: 17.MSMC2_analysis.sh)

# The result files look like the following:
# time_index	left_time_boundary	right_time_boundary	lambda
# 0	                  0	            5.75323e-06	      602.735
# 1	            5.75323e-06	        1.3076e-05      	602.735
# 2	             1.3076e-05	        2.23964e-05	      241.08

a<-read.table("1958_pop_six.final.txt", header=TRUE)
b<-read.table("1963_pop_six.final.txt", header=TRUE)
c<-read.table("2747_pop_six.final.txt", header=TRUE)
d<-read.table("2931_pop_six.final.txt", header=TRUE)
e<-read.table("3111_pop_six.final.txt", header = TRUE)
f<-read.table("2932_pop_six.final.txt", header = TRUE)
g<-read.table("4107_pop_six.final.txt", header = TRUE)
h<-read.table("4117_pop_six.final.txt", header=TRUE)
i<-read.table("4330_pop_six.final.txt", header = TRUE)

plot(afrDat$left_time_boundary/mu*gen, (1/afrDat$lambda)/(2*mu), log="x",ylim=c(0,300000),
     type="n", xlab="Years ago", ylab="effective population size")

lines(afrDat$left_time_boundary/mu*gen, (1/afrDat$lambda)/(2*mu), type="s", col="red")


# An alternative code to plot the results.

mu <- 1*1e-8
gen <- 5

time <- (d$left_time_boundary/mu*gen)
pop.size <- (1/d$lambda)/(2*mu)

plot(time, pop.size, type="s", col="red",
     xlab="log Years before present", 
     ylab="Effective Population Size", 
     log="x")
#

## This is the code used for generating the main figure¨

pdf("MSMC2_six_hap_phased.pdf", height = 8, width = 10, useDingbats = F)
plot(a$left_time_boundary/mu*gen, (1/a$lambda)/(2*mu), log="x",ylim=c(0,350000), type="n", xlab="Years Ago", ylab="Effective Population Size")

lines(a$left_time_boundary/mu*gen, (1/a$lambda)/(2*mu), type="s",col="tomato3", lwd=2.5)
lines(b$left_time_boundary/mu*gen, (1/b$lambda)/(2*mu), type="s",col="blue", lwd=2.5)
lines(c$left_time_boundary/mu*gen, (1/c$lambda)/(2*mu), type="s",col="tan4", lwd=2.5)
lines(d$left_time_boundary/mu*gen, (1/d$lambda)/(2*mu), type="s",col="black", lwd=2.5)
lines(e$left_time_boundary/mu*gen, (1/e$lambda)/(2*mu), type="s",col="burlywood2", lwd=2.5)
lines(f$left_time_boundary/mu*gen, (1/f$lambda)/(2*mu), type="s",col="greenyellow", lwd=2.5)
lines(g$left_time_boundary/mu*gen, (1/g$lambda)/(2*mu), type="s",col="mediumaquamarine", lwd=2.5)
lines(h$left_time_boundary/mu*gen, (1/h$lambda)/(2*mu), type="s",col="darkviolet", lwd=2.5)
lines(i$left_time_boundary/mu*gen, (1/i$lambda)/(2*mu), type="s",col="gray75", lwd=2.5)

legend("topright",legend=c("Central_1958", "Central_1963","Central_2747", "Central_2931", "Central_3111", "South-coast_2932","South-coast_4107", "South-high_4117","South-high_4330"), col=c("tomato3", "blue","tan4","black","burlywood2","greenyellow","mediumaquamarine","darkviolet","gray75"), cex = 0.9, lty=c(1,1), lwd = 3)
dev.off()

lines(CA_R_fixed_rho2_8cores$left_time_boundary/mu*gen, (1/CA_R_fixed_rho2_8cores$lambda)/(2*mu), type="s", col=as.character(Pop_Col_Matrix[grep("CA_R", Pop_Col_Matrix$Population),2]))


# Script for making Cross Coalescent figure

# Read the output files generated by the script '17.2.MSMC2_crosscoal.sh'

# The result files look like the following:
# time_index	left_time_boundary	right_time_boundary	lambda_00	lambda_01	lambda_11
# 0	                0.0	              5.58663e-06	    808.6429	 873.842	 1072.17
# 1	            5.58663e-06	          1.27117e-05	    808.6429	 873.842	 1072.17

a<-read.table("1958_1963_combined.txt", header=TRUE)
b<-read.table("1958_2747_combined.txt", header=TRUE)
c<-read.table("1958_2931_combined.txt", header=TRUE)
d<-read.table("1958_3111_combined.txt", header=TRUE)
e<-read.table("1958_2932_combined.txt", header = TRUE)
f<-read.table("1958_4107_combined.txt", header = TRUE)
g<-read.table("1958_4330_combined.txt", header = TRUE)
h<-read.table("1958_4117_combined.txt", header = TRUE)


i<-read.table("1963_1958_combined.txt", header=TRUE)
j<-read.table("1963_2747_combined.txt", header=TRUE)
k<-read.table("1963_2931_combined.txt", header=TRUE)
l<-read.table("1963_3111_combined.txt", header=TRUE)
m<-read.table("1963_2932_combined.txt", header = TRUE)
n<-read.table("1963_4107_combined.txt", header = TRUE)
g<-read.table("1963_4330_combined.txt", header = TRUE)
h<-read.table("1963_4117_combined.txt", header = TRUE)

i1<-read.table("2747_1958_combined.txt", header=TRUE)
j1<-read.table("2747_1963_combined.txt", header=TRUE)
k1<-read.table("2747_2931_combined.txt", header=TRUE)
l1<-read.table("2747_3111_combined.txt", header=TRUE)
m1<-read.table("2747_2932_combined.txt", header = TRUE)
n1<-read.table("2747_4107_combined.txt", header = TRUE)
g1<-read.table("2747_4330_combined.txt", header = TRUE)
h1<-read.table("2747_4117_combined.txt", header = TRUE)

i2<-read.table("2931_1958_combined.txt", header=TRUE)
j2<-read.table("2931_1963_combined.txt", header=TRUE)
k2<-read.table("2931_2747_combined.txt", header=TRUE)
l2<-read.table("2931_3111_combined.txt", header=TRUE)
m2<-read.table("2931_2932_combined.txt", header = TRUE)
n2<-read.table("2931_4107_combined.txt", header = TRUE)
g2<-read.table("2931_4330_combined.txt", header = TRUE)
h2<-read.table("2931_4117_combined.txt", header = TRUE)

i3<-read.table("2932_1958_combined.txt", header=TRUE)
j3<-read.table("2932_1963_combined.txt", header=TRUE)
k3<-read.table("2932_2747_combined.txt", header=TRUE)
l3<-read.table("2932_2931_combined.txt", header=TRUE)
m3<-read.table("2932_3111_combined.txt", header = TRUE)
n3<-read.table("2932_4107_combined.txt", header = TRUE)
g3<-read.table("2932_4330_combined.txt", header = TRUE)
h3<-read.table("2932_4117_combined.txt", header = TRUE)

i4<-read.table("3111_1958_combined.txt", header=TRUE)
j4<-read.table("3111_1963_combined.txt", header=TRUE)
k4<-read.table("3111_2747_combined.txt", header=TRUE)
l4<-read.table("3111_2931_combined.txt", header=TRUE)
m4<-read.table("3111_2932_combined.txt", header = TRUE)
n4<-read.table("3111_4107_combined.txt", header = TRUE)
g4<-read.table("3111_4330_combined.txt", header = TRUE)
h4<-read.table("3111_4117_combined.txt", header = TRUE)

i5<-read.table("4107_1958_combined.txt", header=TRUE)
j5<-read.table("4107_1963_combined.txt", header=TRUE)
k5<-read.table("4107_2747_combined.txt", header=TRUE)
l5<-read.table("4107_2931_combined.txt", header=TRUE)
m5<-read.table("4107_3111_combined.txt", header = TRUE)
n5<-read.table("4107_2932_combined.txt", header = TRUE)
g5<-read.table("4107_4330_combined.txt", header = TRUE)
h5<-read.table("4107_4117_combined.txt", header = TRUE)

i6<-read.table("4117_1958_combined.txt", header=TRUE)
j6<-read.table("4117_1963_combined.txt", header=TRUE)
k6<-read.table("4117_2747_combined.txt", header=TRUE)
l6<-read.table("4117_2931_combined.txt", header=TRUE)
m6<-read.table("4117_3111_combined.txt", header = TRUE)
n6<-read.table("4117_2932_combined.txt", header = TRUE)
g6<-read.table("4117_4107_combined.txt", header = TRUE)
h6<-read.table("4117_4330_combined.txt", header = TRUE)

i7<-read.table("4330_1958_combined.txt", header=TRUE)
j7<-read.table("4330_1963_combined.txt", header=TRUE)
k7<-read.table("4330_2747_combined.txt", header=TRUE)
l7<-read.table("4330_2931_combined.txt", header=TRUE)
m7<-read.table("4330_3111_combined.txt", header = TRUE)
n7<-read.table("4330_2932_combined.txt", header = TRUE)
g7<-read.table("4330_4107_combined.txt", header = TRUE)
h7<-read.table("4330_4117_combined.txt", header = TRUE)

# Plot the figure

pdf("MSMC2_cross_coal.pdf", height = 14, width = 12, useDingbats = F)
par(mfrow=c(5,2))
#layout(matrix(c(1,2,3,4,5,6,7,8,9,9), nrow = 5, byrow = TRUE))
plot(a$left_time_boundary/mu*gen, 2 * a$lambda_01 / (a$lambda_00 + a$lambda_11),
     log = "x",ylim = c(0,1.1), type="n", xlab="Years ago", ylab="relative cross-coalescence rate")
lines(a$left_time_boundary/mu*gen, 2 * a$lambda_01 / (a$lambda_00 + a$lambda_11), type="l", col="tomato3", lwd=3)
lines(b$left_time_boundary/mu*gen, 2 * b$lambda_01 / (b$lambda_00 + b$lambda_11), type="l", col="blue",lwd=3)
lines(c$left_time_boundary/mu*gen, 2 * c$lambda_01 / (c$lambda_00 + c$lambda_11), type="l", col="tan2",lwd=3)
lines(d$left_time_boundary/mu*gen, 2 * d$lambda_01 / (d$lambda_00 + d$lambda_11), type="l", col="black",lwd=3)
lines(e$left_time_boundary/mu*gen, 2 * e$lambda_01 / (e$lambda_00 + e$lambda_11), type="l", col="mediumorchid1",lwd=3)
lines(f$left_time_boundary/mu*gen, 2 * f$lambda_01 / (f$lambda_00 + f$lambda_11), type="l", col="greenyellow",lwd=3)
lines(g$left_time_boundary/mu*gen, 2 * g$lambda_01 / (g$lambda_00 + g$lambda_11), type="l", col="darkviolet",lwd=3)
lines(h$left_time_boundary/mu*gen, 2 * h$lambda_01 / (h$lambda_00 + h$lambda_11), type="l", col="gray75",lwd=3)
legend("bottomright",legend=c("1958_1963", "1958_2747", "1958_2931","1958_3111","1958_2932","1958_4107","1958_4330","1958_4117"), col=c("tomato3", "blue","tan2","black","mediumorchid1","greenyellow","darkviolet","gray75"), cex = 0.9, lty=c(1,1))


plot(i$left_time_boundary/mu*gen, 2 * i$lambda_01 / (i$lambda_00 + i$lambda_11),
     log = "x",ylim = c(0,1.1), type="n", xlab="Years ago", ylab="relative cross-coalescence rate")
lines(i$left_time_boundary/mu*gen, 2 * i$lambda_01 / (i$lambda_00 + i$lambda_11), type="l", col="tomato3", lwd=3)
lines(j$left_time_boundary/mu*gen, 2 * j$lambda_01 / (j$lambda_00 + j$lambda_11), type="l", col="blue",lwd=3)
lines(k$left_time_boundary/mu*gen, 2 * k$lambda_01 / (k$lambda_00 + k$lambda_11), type="l", col="tan2",lwd=3)
lines(l$left_time_boundary/mu*gen, 2 * l$lambda_01 / (l$lambda_00 + l$lambda_11), type="l", col="black",lwd=3)
lines(m$left_time_boundary/mu*gen, 2 * m$lambda_01 / (m$lambda_00 + m$lambda_11), type="l", col="mediumorchid1",lwd=3)
lines(n$left_time_boundary/mu*gen, 2 * n$lambda_01 / (n$lambda_00 + n$lambda_11), type="l", col="greenyellow",lwd=3)
lines(g$left_time_boundary/mu*gen, 2 * g$lambda_01 / (g$lambda_00 + g$lambda_11), type="l", col="darkviolet",lwd=3)
lines(h$left_time_boundary/mu*gen, 2 * h$lambda_01 / (h$lambda_00 + h$lambda_11), type="l", col="gray75",lwd=3)
legend("bottomright",legend=c("1963_1958", "1963_2747", "1963_2931","1963_3111","1963_2932","1963_4107", "1963_4117","1963_4330"), col=c("tomato3", "blue","tan2","black","mediumorchid1","greenyellow","darkviolet","gray75"), cex = 0.9, lty=c(1,1))

plot(i1$left_time_boundary/mu*gen, 2 * i1$lambda_01 / (i1$lambda_00 + i1$lambda_11),
     log = "x",ylim = c(0,1.1), type="n", xlab="Years ago", ylab="relative cross-coalescence rate")
lines(i1$left_time_boundary/mu*gen, 2 * i1$lambda_01 / (i1$lambda_00 + i1$lambda_11), type="l", col="tomato3", lwd=3)
lines(j1$left_time_boundary/mu*gen, 2 * j1$lambda_01 / (j1$lambda_00 + j1$lambda_11), type="l", col="blue",lwd=3)
lines(k1$left_time_boundary/mu*gen, 2 * k1$lambda_01 / (k1$lambda_00 + k1$lambda_11), type="l", col="tan2",lwd=3)
lines(l1$left_time_boundary/mu*gen, 2 * l1$lambda_01 / (l1$lambda_00 + l1$lambda_11), type="l", col="black",lwd=3)
lines(m1$left_time_boundary/mu*gen, 2 * m1$lambda_01 / (m1$lambda_00 + m1$lambda_11), type="l", col="mediumorchid1",lwd=3)
lines(n1$left_time_boundary/mu*gen, 2 * n1$lambda_01 / (n1$lambda_00 + n1$lambda_11), type="l", col="greenyellow",lwd=3)
lines(g1$left_time_boundary/mu*gen, 2 * g1$lambda_01 / (g1$lambda_00 + g1$lambda_11), type="l", col="darkviolet",lwd=3)
lines(h1$left_time_boundary/mu*gen, 2 * h1$lambda_01 / (h1$lambda_00 + h1$lambda_11), type="l", col="gray75",lwd=3)
legend("bottomright",legend=c("2747_1958", "2747_1963", "2747_2931","2747_3111","2747_2932","2747_4107","2747_4117","2747_4330"), col=c("tomato3", "blue","tan2","black","mediumorchid1","greenyellow","darkviolet","gray75"), cex = 0.9, lty=c(1,1))

plot(i2$left_time_boundary/mu*gen, 2 * i2$lambda_01 / (i2$lambda_00 + i2$lambda_11),
     log = "x",ylim = c(0,1.1), type="n", xlab="Years ago", ylab="relative cross-coalescence rate")
lines(i2$left_time_boundary/mu*gen, 2 * i2$lambda_01 / (i2$lambda_00 + i2$lambda_11), type="l", col="tomato3", lwd=3)
lines(j2$left_time_boundary/mu*gen, 2 * j2$lambda_01 / (j2$lambda_00 + j2$lambda_11), type="l", col="blue",lwd=3)
lines(k2$left_time_boundary/mu*gen, 2 * k2$lambda_01 / (k2$lambda_00 + k2$lambda_11), type="l", col="tan2",lwd=3)
lines(l2$left_time_boundary/mu*gen, 2 * l2$lambda_01 / (l2$lambda_00 + l2$lambda_11), type="l", col="black",lwd=3)
lines(m2$left_time_boundary/mu*gen, 2 * m2$lambda_01 / (m2$lambda_00 + m2$lambda_11), type="l", col="mediumorchid1",lwd=3)
lines(n2$left_time_boundary/mu*gen, 2 * n2$lambda_01 / (n2$lambda_00 + n2$lambda_11), type="l", col="greenyellow",lwd=3)
lines(g2$left_time_boundary/mu*gen, 2 * g2$lambda_01 / (g2$lambda_00 + g2$lambda_11), type="l", col="darkviolet",lwd=3)
lines(h2$left_time_boundary/mu*gen, 2 * h2$lambda_01 / (h2$lambda_00 + h2$lambda_11), type="l", col="gray75",lwd=3)
legend("bottomright",legend=c("2931_1958", "2931_1963", "2931_2747","2931_3111","2931_2932","2391_4107","2931_4117","2391_4330"), col=c("tomato3", "blue","tan2","black","mediumorchid1","greenyellow","darkviolet","gray75"), cex = 0.9, lty=c(1,1))

plot(i3$left_time_boundary/mu*gen, 2 * i3$lambda_01 / (i3$lambda_00 + i3$lambda_11),
     log = "x",ylim = c(0,1.1), type="n", xlab="Years ago", ylab="relative cross-coalescence rate")
lines(i3$left_time_boundary/mu*gen, 2 * i3$lambda_01 / (i3$lambda_00 + i3$lambda_11), type="l", col="tomato3", lwd=3)
lines(j3$left_time_boundary/mu*gen, 2 * j3$lambda_01 / (j3$lambda_00 + j3$lambda_11), type="l", col="blue",lwd=3)
lines(k3$left_time_boundary/mu*gen, 2 * k3$lambda_01 / (k3$lambda_00 + k3$lambda_11), type="l", col="tan2",lwd=3)
lines(l3$left_time_boundary/mu*gen, 2 * l3$lambda_01 / (l3$lambda_00 + l3$lambda_11), type="l", col="black",lwd=3)
lines(m3$left_time_boundary/mu*gen, 2 * m3$lambda_01 / (m3$lambda_00 + m3$lambda_11), type="l", col="mediumorchid1",lwd=3)
lines(n3$left_time_boundary/mu*gen, 2 * n3$lambda_01 / (n3$lambda_00 + n3$lambda_11), type="l", col="greenyellow",lwd=3)
lines(g3$left_time_boundary/mu*gen, 2 * g3$lambda_01 / (g3$lambda_00 + g3$lambda_11), type="l", col="darkviolet",lwd=3)
lines(h3$left_time_boundary/mu*gen, 2 * h3$lambda_01 / (h3$lambda_00 + h3$lambda_11), type="l", col="gray75",lwd=3)
legend("bottomright",legend=c("2932_1958", "2932_1963", "2932_2747","2932_2931","2932_3111","2932_4107","2932_4117","2392_4330"), col=c("tomato3", "blue","tan2","black","mediumorchid1","greenyellow","darkviolet","gray75"), cex = 0.9, lty=c(1,1))

plot(i4$left_time_boundary/mu*gen, 2 * i4$lambda_01 / (i4$lambda_00 + i4$lambda_11),
     log = "x",ylim = c(0,1.1), type="n", xlab="Years ago", ylab="relative cross-coalescence rate")
lines(i4$left_time_boundary/mu*gen, 2 * i4$lambda_01 / (i4$lambda_00 + i4$lambda_11), type="l", col="tomato3", lwd=3)
lines(j4$left_time_boundary/mu*gen, 2 * j4$lambda_01 / (j4$lambda_00 + j4$lambda_11), type="l", col="blue",lwd=3)
lines(k4$left_time_boundary/mu*gen, 2 * k4$lambda_01 / (k4$lambda_00 + k4$lambda_11), type="l", col="tan2",lwd=3)
lines(l4$left_time_boundary/mu*gen, 2 * l4$lambda_01 / (l4$lambda_00 + l4$lambda_11), type="l", col="black",lwd=3)
lines(m4$left_time_boundary/mu*gen, 2 * m4$lambda_01 / (m4$lambda_00 + m4$lambda_11), type="l", col="mediumorchid1",lwd=3)
lines(n4$left_time_boundary/mu*gen, 2 * n4$lambda_01 / (n4$lambda_00 + n4$lambda_11), type="l", col="greenyellow",lwd=3)
lines(g4$left_time_boundary/mu*gen, 2 * g4$lambda_01 / (g4$lambda_00 + g4$lambda_11), type="l", col="darkviolet",lwd=3)
lines(h4$left_time_boundary/mu*gen, 2 * h4$lambda_01 / (h4$lambda_00 + h4$lambda_11), type="l", col="gray75",lwd=3)
legend("bottomright",legend=c("3111_1958", "3111_1963", "3111_2747","3111_2931","3111_2932","3111_4107","3111_4117","3111_4330"), col=c("tomato3", "blue","tan2","black","mediumorchid1","greenyellow","darkviolet","gray75"), cex = 0.9, lty=c(1,1))

plot(i5$left_time_boundary/mu*gen, 2 * i5$lambda_01 / (i5$lambda_00 + i5$lambda_11),
     log = "x",ylim = c(0,1.1), type="n", xlab="Years ago", ylab="relative cross-coalescence rate")
lines(i5$left_time_boundary/mu*gen, 2 * i5$lambda_01 / (i5$lambda_00 + i5$lambda_11), type="l", col="tomato3", lwd=3)
lines(j5$left_time_boundary/mu*gen, 2 * j5$lambda_01 / (j5$lambda_00 + j5$lambda_11), type="l", col="blue",lwd=3)
lines(k5$left_time_boundary/mu*gen, 2 * k5$lambda_01 / (k5$lambda_00 + k5$lambda_11), type="l", col="tan2",lwd=3)
lines(l5$left_time_boundary/mu*gen, 2 * l5$lambda_01 / (l5$lambda_00 + l5$lambda_11), type="l", col="black",lwd=3)
lines(m5$left_time_boundary/mu*gen, 2 * m5$lambda_01 / (m5$lambda_00 + m5$lambda_11), type="l", col="mediumorchid1",lwd=3)
lines(n5$left_time_boundary/mu*gen, 2 * n5$lambda_01 / (n5$lambda_00 + n5$lambda_11), type="l", col="greenyellow",lwd=3)
lines(g5$left_time_boundary/mu*gen, 2 * g5$lambda_01 / (g5$lambda_00 + g5$lambda_11), type="l", col="darkviolet",lwd=3)
lines(h5$left_time_boundary/mu*gen, 2 * h5$lambda_01 / (h5$lambda_00 + h5$lambda_11), type="l", col="gray75",lwd=3)
legend("bottomright",legend=c("4107_1958", "4107_1963", "4107_2747","4107_2931","4107_3111","4107_2932","4107_4117","4107_4330"), col=c("tomato3", "blue","tan2","black","mediumorchid1","greenyellow","darkviolet","gray75"), cex = 0.9, lty=c(1,1))

plot(i6$left_time_boundary/mu*gen, 2 * i6$lambda_01 / (i6$lambda_00 + i6$lambda_11),
     log = "x",ylim = c(0,1.1), type="n", xlab="Years ago", ylab="relative cross-coalescence rate")
lines(i6$left_time_boundary/mu*gen, 2 * i6$lambda_01 / (i6$lambda_00 + i6$lambda_11), type="l", col="tomato3", lwd=3)
lines(j6$left_time_boundary/mu*gen, 2 * j6$lambda_01 / (j6$lambda_00 + j6$lambda_11), type="l", col="blue",lwd=3)
lines(k6$left_time_boundary/mu*gen, 2 * k6$lambda_01 / (k6$lambda_00 + k6$lambda_11), type="l", col="tan2",lwd=3)
lines(l6$left_time_boundary/mu*gen, 2 * l6$lambda_01 / (l6$lambda_00 + l6$lambda_11), type="l", col="black",lwd=3)
lines(m6$left_time_boundary/mu*gen, 2 * m6$lambda_01 / (m6$lambda_00 + m6$lambda_11), type="l", col="mediumorchid1",lwd=3)
lines(n6$left_time_boundary/mu*gen, 2 * n6$lambda_01 / (n6$lambda_00 + n6$lambda_11), type="l", col="greenyellow",lwd=3)
lines(g6$left_time_boundary/mu*gen, 2 * g6$lambda_01 / (g6$lambda_00 + g6$lambda_11), type="l", col="darkviolet",lwd=3)
lines(h6$left_time_boundary/mu*gen, 2 * h6$lambda_01 / (h6$lambda_00 + h6$lambda_11), type="l", col="gray75",lwd=3)
legend("bottomright",legend=c("4117_1958", "4117_1963", "4117_2747","4117_2931","4117_3111","4117_2932","4117_4107","4117_4330"), col=c("tomato3", "blue","tan2","black","mediumorchid1","greenyellow","darkviolet","gray75"), cex = 0.9, lty=c(1,1))

plot(i7$left_time_boundary/mu*gen, 2 * i7$lambda_01 / (i7$lambda_00 + i7$lambda_11),
     log = "x",ylim = c(0,1.1), type="n", xlab="Years ago", ylab="relative cross-coalescence rate")
lines(i7$left_time_boundary/mu*gen, 2 * i7$lambda_01 / (i7$lambda_00 + i7$lambda_11), type="l", col="tomato3", lwd=3)
lines(j7$left_time_boundary/mu*gen, 2 * j7$lambda_01 / (j7$lambda_00 + j7$lambda_11), type="l", col="blue",lwd=3)
lines(k7$left_time_boundary/mu*gen, 2 * k7$lambda_01 / (k7$lambda_00 + k7$lambda_11), type="l", col="tan2",lwd=3)
lines(l7$left_time_boundary/mu*gen, 2 * l7$lambda_01 / (l7$lambda_00 + l7$lambda_11), type="l", col="black",lwd=3)
lines(m7$left_time_boundary/mu*gen, 2 * m7$lambda_01 / (m7$lambda_00 + m7$lambda_11), type="l", col="mediumorchid1",lwd=3)
lines(n7$left_time_boundary/mu*gen, 2 * n7$lambda_01 / (n7$lambda_00 + n7$lambda_11), type="l", col="greenyellow",lwd=3)
lines(g7$left_time_boundary/mu*gen, 2 * g7$lambda_01 / (g7$lambda_00 + g7$lambda_11), type="l", col="darkviolet",lwd=3)
lines(h7$left_time_boundary/mu*gen, 2 * h7$lambda_01 / (h7$lambda_00 + h7$lambda_11), type="l", col="gray75",lwd=3)
legend("bottomright",legend=c("4330_1958", "4330_1963", "4330_2747","4330_2931","4330_3111","4330_2932","4330_4107","4330_4117"), col=c("tomato3", "blue","tan2","black","mediumorchid1","greenyellow","darkviolet","gray75"), cex = 0.9, lty=c(1,1))

dev.off()

